"""add index to vibe members

Revision ID: 2c15a765335f
Revises: e7177a370158
Create Date: 2026-02-27 11:50:22.216490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c15a765335f'
down_revision: Union[str, Sequence[str], None] = 'e7177a370158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vibe_members_vibe_user', 'vibe_members', ['vibe_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vibe_members_vibe_user', table_name='vibe_members')
    # ### end Alembic commands ###
