"""Add user influence score

Revision ID: 5beb80ae06dd
Revises: 62cb1aface74
Create Date: 2026-03-06 21:50:35.520938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5beb80ae06dd'
down_revision: Union[str, Sequence[str], None] = '62cb1aface74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('influence_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'influence_score')
    # ### end Alembic commands ###
