"""Add user interest scores

Revision ID: 62cb1aface74
Revises: 7d973c9e4b3b
Create Date: 2026-03-06 21:36:42.940331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cb1aface74'
down_revision: Union[str, Sequence[str], None] = '7d973c9e4b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interest_scores',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vibe_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'vibe_id')
    )
    op.create_index('idx_interest_user_vibe', 'user_interest_scores', ['user_id', 'vibe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_interest_user_vibe', table_name='user_interest_scores')
    op.drop_table('user_interest_scores')
    # ### end Alembic commands ###
