"""analytics

Revision ID: 7d973c9e4b3b
Revises: 8ffead3e022a
Create Date: 2026-03-06 21:29:43.446502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d973c9e4b3b'
down_revision: Union[str, Sequence[str], None] = '8ffead3e022a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'score')
    op.drop_column('posts', 'comments_count')
    op.drop_column('posts', 'likes_count')
    op.drop_table('feed_events')
    # ### end Alembic commands ###
