"""create vibes and vibe_members tables

Revision ID: 992f40340c15
Revises: f38d9b078cd8
Create Date: 2026-02-27 11:08:24.475856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992f40340c15'
down_revision: Union[str, Sequence[str], None] = 'f38d9b078cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vibes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vibes_name'), 'vibes', ['name'], unique=False)
    op.create_table('vibe_members',
    sa.Column('vibe_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vibe_id'], ['vibes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vibe_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vibe_members')
    op.drop_index(op.f('ix_vibes_name'), table_name='vibes')
    op.drop_table('vibes')
    # ### end Alembic commands ###
